language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ng-poly' ]; then cd .. && eval "mv $currentfolder generator-ng-poly" && cd generator-ng-poly; fi
  - npm install -g gulp
after_success: npm run-script coveralls